### ISSUE TITLE
Share dataset

### ISSUE THREAD

**Issue by wuxiubozuishuai** [lcylmhlcy/violence-c3d-caffe#2]
Thank you very much for sharing your code.
I would like to ask if the dataset is your own? Can you share it with me? 
Looking forward to your reply

**Comment by wuxiubozuishuai** [comment]
@lcylmhlcy

**Comment by lcylmhlcy** [comment]
> Thank you very much for sharing your code.
> I would like to ask if the dataset is your own? Can you share it with me?
> Looking forward to your reply

**Comment by lcylmhlcy** [comment]
> Thank you very much for sharing your code.
> I would like to ask if the dataset is your own? Can you share it with me?
> Looking forward to your reply

I am uploading to BaiduYun.

**Comment by wuxiubozuishuai** [comment]
The data set you made is very interesting. Can I make a friend with you ? My email address is 765469818@qq.com. I hope to get your reply.  @lcylmhlcy
